version: 2

models:
  - name: stg_events
    description: event details such as session id, type and page.
  - name: stg_orders
    description: order details such as address, cost, tracking, shipping and delivery.
  - name: stg_users
    description: User details such as name, address, email and phone.
  - name: stg_address
    description: address details such as street, state, zip and country.
  - name: stg_products
    description: product detials such as name, price and inventory.
  - name: stg_order_items
    description: order item details such as quantity.
  - name: stg_promos
    description: promo details such as discount and status.