version: 2

models:
  - name: stg_greenery__events
    description: event details such as session id, type and page. 
   
  - name: stg_greenery__orders
    description: order details such as address, cost, tracking, shipping and delivery
      
  - name: stg_greenery__users
    description: User details such as name, address, email and phone. 
  
  - name: stg_greenery__addresses
    description: address details such as street, state, zip and country.

  - name: stg_greenery__products
    description: product detials such as name, price and inventory. 

  - name: stg_greenery__order_items
    description: order item details such as quantity. 

  - name: stg_greenery__promos
    description: promo details such as discount and status.       