version: 2

models:
  - name: stg_greenery__events
    description: event details such as session id, type and page. 
    columns:
      - name: event_id
      - name: session_id
      - name: user_id
      - name: page_url
      - name: created_at
      - name: event_type
      - name: order_id
      - name: product_id

  - name: stg_greenery__orders
    description: order details such as address, cost, tracking, shipping and delivery
    columns:
      - name: order_id
      - name: user_id
      - name: promo_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total 
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status
  
  - name: stg_greenery__users
    description: User details such as name, address, email and phone. 
    columns:
      - name: user_id
      - name: first_name
      - name: last_name
      - name:  email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id

  - name: stg_greenery__addresses
    description: address details such as street, state, zip and country.
    columns:
      - name: address_id 
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_greenery__products
    description: product detials such as name, price and inventory. 
    columns:
      - name: product_id
      - name: name
      - name: price
      - name: inventory

  - name: stg_greenery__order_items
    description: order item details such as quantity. 
    columns:
      - name: order_id 
      - name: product_id
      - name: quantity      

  - name: stg_greenery__promos
    description: promo details such as discount and status. 
    columns:
      - name: promo_id
      - name: discount
      - name: status
      